### ISSUE TITLE
ABOUT 3DHP

### ISSUE THREAD

**Issue by Aerikervalid** [paTRICK-swk/P-STMO#28]
![image](https://github.com/paTRICK-swk/P-STMO/assets/138544094/bd618324-b7f4-4fdd-a9ee-75c8f68595ed)

Hi, Great Job.  I want to ask why my 3DHP dataset doesn't have a valid_frame metric. Is it because I didn't process the dataset, or because my downloaded dataset has an error. Looking forward to your reply, thank you very much! 
Finally, congratulations, your new job has been accepted by iccv2023, which I havenoticed long on. Great job!

**Comment by paTRICK-swk** [comment]
As stated in the readme, if you want to get the PCK and AUC metrics on this dataset, you also need to download the original dataset from the [official website](https://vcai.mpi-inf.mpg.de/3dhp-dataset/). After downloading the dataset, you can place the TS1 to TS6 folders in the test set under the ./3dhp_test folder in this repo.  Because the `valid_frame` is provided in `./TS1~6/annot_dat.mat`.

**Comment by Aerikervalid** [comment]
thanks
